version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    command: server /data --console-address ":9001"
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: 61b526d0
      MINIO_SECRET_KEY: 61b526d0
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
